services:
  - type: web
    name: data-analyst-agent
    env: docker
    plan: starter
    healthCheckPath: /
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: huggingface-cache
      mountPath: /huggingface_cache
      sizeGB: 5
